### ISSUE TITLE
arm/v7 or arm/v8 build not available on ghcr.io

### ISSUE THREAD

**Issue by itavero** [yoori/flare-bypasser#21]
I wanted to give this a go on my QNAP NAS, which has an ARM64 processor (`linux/arm/v8`).

In the workflow files I did see `linux/arm/v7` mentioned, but unfortunately I cannot pull that particular architecture from GitHub (e.g. `ghcr.io/yoori/flare-bypasser:latest`).
The images published there only contain the `linux/amd64` builds.

Would it be possible to provide these other builds as well?

It seems like the step to merge the different builds is missing.
I'm not an expert, but I do [something similar](https://github.com/itavero/peblar2mqtt/blob/main/.github/workflows/docker-publish.yml) in one of my projects. (Disclaimer: Copilot and Google helped me on that one 😅)

**Comment by yoori** [comment]
Hi, I try )
Here some problem with opencv installation to arm7 - I will try to solve at next 2-3 days

**Comment by yoori** [comment]
Fixed :
arm/v7, arm/v8 is available now.
problem with multi arch manifest fixed.

**Comment by itavero** [comment]
Pulling now works.. Not sure if it's arm/v7 specific, but I do get an error about the Chrome binary being non-existent when te container starts.
I'm also not getting any response when using cURL to test the server (though that may be an error in my docker compose still).

```
/opt/flare_bypasser/bin/FlareBypasserRun.sh: line 158: /usr/bin/chrome: No such file or directory
Run server 0.1.43, chrome: , extensions: , add params: 
2024-11-25 20:39:31,094 [flare_bypasser.flare_bypass_server] [INFO]: Start flare_bypass server:
  version: 0.1.43
  python version = 3.11.10.final.0
  os = Linux 5.10.60-qnap #1 SMP Fri Oct 25 15:05:58 CST 2024
  docker = true
  arch = aarch64
  processor = 
[2024-11-25 20:39:31 +0100] [26] [INFO] Starting gunicorn 23.0.0
[2024-11-25 20:39:31 +0100] [26] [INFO] Listening at: http://0.0.0.0:8080 (26)
[2024-11-25 20:39:31 +0100] [26] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-11-25 20:39:31 +0100] [29] [INFO] Booting worker with pid: 29
[2024-11-25 20:39:31 +0100] [29] [INFO] Started server process [29]
[2024-11-25 20:39:31 +0100] [29] [INFO] Waiting for application startup.
[2024-11-25 20:39:31 +0100] [29] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2024-11-25 20:39:31 +0100] [29] [INFO] Application startup complete.
```

**Comment by yoori** [comment]
I don’t think that chrome error is critical - I think it have other path on aarch64, I will check.
About curl : what show curl with -v option ?

**Comment by itavero** [comment]
The no-response part was probably an error in my configuration.
Just started the container directly from the command line (`docker run -it --rm ...`) and then it did respond.. although with a timeout:

```
2024-11-25 20:04:30,785 [flare_bypasser.flare_bypass_server] [INFO]: Start solve_tasks = [<function process_solve_request.<locals>.<lambda> at 0xfffba9f86e80>]
2024-11-25 20:04:30,786 [flare_bypasser.flare_bypass_server] [INFO]: fork #0, Solve start
2024-11-25 20:04:30,786 [flare_bypasser.flare_bypasser] [INFO]: fork #0, Solve request: {'cmd': 'request.get', 'url': 'http://www.google.nl/', 'cookies': [], 'max_timeout': 60.0, 'proxy': None, 'params': None}
2024-11-25 20:04:30,931 [zendriver_flare_bypasser.core.browser] [INFO]: starting
	executable :/bin/chromium

arguments:
--remote-allow-origins=*
	--no-first-run
	--no-service-autorun
	--no-default-browser-check
	--homepage=about:blank
	--no-pings
	--password-store=basic
	--disable-infobars
	--disable-breakpad
	--disable-component-update
	--disable-backgrounding-occluded-windows
	--disable-renderer-backgrounding
	--disable-background-networking
	--disable-dev-shm-usage
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--disable-search-engine-choice-screen
	--user-data-dir=/tmp/uc_gqg6b_cv
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--user-data-dir=/tmp/70c0cdf7-e26a-437b-80a1-a1e299d486ae
	--no-sandbox
	--remote-debugging-host=127.0.0.1
	--remote-debugging-port=57777
2024-11-25 20:04:32,775 [zendriver_flare_bypasser.core.browser] [INFO]: enabling autodiscover targets
2024-11-25 20:04:32,964 [flare_bypasser.flare_bypasser] [INFO]: fork #0, New instance of webdriver has been created to perform the request (proxy=None), timeout=60.0
2024-11-25 20:05:30,787 [flare_bypasser.flare_bypasser] [INFO]: fork #0, Close webdriver
Processing timeout (max_timeout=60.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 289, in _resolve_challenge
    return await self._resolve_challenge_impl(req, start_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 470, in _resolve_challenge_impl
    challenge_found = await self._check_challenge()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 333, in _check_challenge
    page_title = await self._driver.title()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 122, in title
    res = await self._page.select("title", timeout=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/tab.py", line 237, in select
    item = await self.query_selector(selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/tab.py", line 424, in query_selector
    doc: cdp.dom.Node = await self.send(cdp.dom.get_document(-1, True))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/connection.py", line 435, in send
    return await tx
           ^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 257, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), req.max_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 250, in process_solve_request
    solve_response, _skipped_results, _exceptions = await wait_first_non_exception(solve_tasks)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 147, in wait_first_non_exception
    raise e
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 139, in wait_first_non_exception
    res = await f
          ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 172, in solve
    return await solver.solve(solve_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 260, in solve
    raise Exception("Processing timeout (max_timeout=" + str(req.max_timeout) + ")")
Exception: Processing timeout (max_timeout=60.0)
```

**Comment by yoori** [comment]
Please, try latest version after [this fix](https://github.com/yoori/flare-bypasser/commit/ef46dc721424204212f3c77b72bf38775a0cb8e3)

**Comment by itavero** [comment]
@yoori Thanks for the update. I still get an error though it is a different one.

```
$ docker pull ghcr.io/yoori/flare-bypasser:latest
latest: Pulling from yoori/flare-bypasser
Digest: sha256:95f3e89512a9727da5a4e580ac8ec5c325f65c00c04e3e1b0e975c59ad33f0cd
Status: Image is up to date for ghcr.io/yoori/flare-bypasser:latest
ghcr.io/yoori/flare-bypasser:latest
$ docker run -it --rm -p 8765:8080 ghcr.io/yoori/flare-bypasser:latest
Starting system message bus: dbus.
/opt/flare_bypasser/bin/FlareBypasserRun.sh: line 169: /usr/bin/chrome: No such file or directory
Run server 0.1.53, chrome: , extensions: , add params: 
2024-12-16 20:03:23,166 [flare_bypasser.flare_bypass_server] [INFO]: Start flare_bypass server:
  version: 0.1.53
  python version = 3.11.11.final.0
  os = Linux 5.10.60-qnap #1 SMP Thu Nov 14 05:23:23 CST 2024
  docker = true
  arch = aarch64
  processor = 
[2024-12-16 20:03:23 +0000] [44] [INFO] Starting gunicorn 23.0.0
[2024-12-16 20:03:23 +0000] [44] [INFO] Listening at: http://0.0.0.0:8080 (44)
[2024-12-16 20:03:23 +0000] [44] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-12-16 20:03:23 +0000] [47] [INFO] Booting worker with pid: 47
[2024-12-16 20:03:23 +0000] [47] [INFO] Started server process [47]
[2024-12-16 20:03:23 +0000] [47] [INFO] Waiting for application startup.
[2024-12-16 20:03:23 +0000] [47] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2024-12-16 20:03:23 +0000] [47] [INFO] Application startup complete.
2024-12-16 20:03:33,359 [flare_bypasser.flare_bypass_server] [INFO]: Start solve_tasks = [<function process_solve_request.<locals>.<lambda> at 0xffff69b5e2a0>]
2024-12-16 20:03:33,361 [flare_bypasser.flare_bypass_server] [INFO]: fork #0, Solve start
2024-12-16 20:03:33,361 [flare_bypasser.flare_bypasser] [INFO]: fork #0, Solve request: {'cmd': 'request.get', 'url': 'http://www.google.nl/', 'cookies': [], 'max_timeout': 60.0, 'proxy': None, 'params': None}
2024-12-16 20:03:33,470 [zendriver_flare_bypasser.core.browser] [INFO]: starting
	executable :/bin/chromium

arguments:
--remote-allow-origins=*
	--no-first-run
	--no-service-autorun
	--no-default-browser-check
	--homepage=about:blank
	--no-pings
	--password-store=basic
	--disable-infobars
	--disable-breakpad
	--disable-component-update
	--disable-backgrounding-occluded-windows
	--disable-renderer-backgrounding
	--disable-background-networking
	--disable-dev-shm-usage
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--disable-search-engine-choice-screen
	--user-data-dir=/tmp/uc_7viy0tk5
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--user-data-dir=/tmp/ea90c7c9-c730-40e5-b41a-06aedea80a99
	--ignore-certificate-errors
	--ignore-urlfetcher-cert-requests
	--no-sandbox
	--remote-debugging-host=127.0.0.1
	--remote-debugging-port=40451
2024-12-16 20:03:33,475 [zendriver_flare_bypasser.core.browser] [INFO]: starting
	executable :/bin/chromium

arguments:
--remote-allow-origins=*
	--no-first-run
	--no-service-autorun
	--no-default-browser-check
	--homepage=about:blank
	--no-pings
	--password-store=basic
	--disable-infobars
	--disable-breakpad
	--disable-component-update
	--disable-backgrounding-occluded-windows
	--disable-renderer-backgrounding
	--disable-background-networking
	--disable-dev-shm-usage
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--disable-search-engine-choice-screen
	--user-data-dir=/tmp/uc_slox493s
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--user-data-dir=/tmp/da6e0ed3-dc95-4326-b3e0-2c89179948d8
	--ignore-certificate-errors
	--ignore-urlfetcher-cert-requests
	--no-sandbox
	--remote-debugging-host=127.0.0.1
	--remote-debugging-port=58205
2024-12-16 20:03:36,278 [flare_bypasser.flare_bypasser] [INFO]: fork #0, Close webdriver
2024-12-16 20:03:36,278 [flare_bypasser.flare_bypasser] [ERROR]: fork #0, Error solving the challenge. On platform linux at step 'browser init': 
On user-agent getting: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 166, in get_user_agent
    return await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 560, in get_user_agent
    driver: BrowserWrapper = await BrowserWrapper.create(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 115, in create
    zendriver_driver = await zendriver.Browser.create(config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/browser.py", line 92, in create
    await instance.start()
  File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/browser.py", line 372, in start
    await self._stop_process()
  File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/browser.py", line 590, in _stop_process
    self._process.terminate()
  File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 143, in terminate
    self._transport.terminate()
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 149, in terminate
    self._check_proc()
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 142, in _check_proc
    raise ProcessLookupError()
ProcessLookupError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 279, in process_solve_request
    (solve_response, _skipped_results, _exceptions), user_agent = await asyncio.gather(
                                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 176, in get_user_agent
    raise Exception("On user-agent getting: " + str(e)) from e
Exception: On user-agent getting: 

```

**Comment by douglascamata** [comment]
Basically the image for arm64 does not contain the Chrome binary, which is essential for it to do its job.

**Comment by KingWaffleIII** [comment]
Also get the same error on RPI3 with the modified Dockerfile from #44
