### ISSUE TITLE
How do I adapt or use it in openbullet2?

### ISSUE THREAD

**Issue by madamesr1337** [yoori/flare-bypasser#3]
I recently saw your comment on the ob2 forum and wanted to know how to implement it. I was able to make it listen on 127.0.0.1:8000 in ob2 and in the windows 10 cmd

PS C:\> flare_bypass_server
←[32mINFO←[0m:     Started server process [←[36m29524←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:63267 - "←[1mGET / HTTP/1.1←[0m" ←[31m404 Not Found←[0m
←[32mINFO←[0m:     127.0.0.1:63460 - "←[1mGET / HTTP/1.1←[0m" ←[31m404 Not Found←[0m
←[32mINFO←[0m:     127.0.0.1:63475 - "←[1mGET / HTTP/1.1←[0m" ←[31m404 Not Found←[0m

I didn't quite understand how it's used, so I tried to send the URL in the headers and have the bypass understand it. But I don't know if I did it right. Could you explain to me how it's adapted or used in ob2? Thanks and good work with this great tool!

![image](https://github.com/user-attachments/assets/7600e007-2d6f-4a0c-b8d1-1e33f14cb9c9)

http://localhost:8000

cmd: request.get
url: https://www.pxxxxx.net/jwl/public/home-en.jsp
maxTimeout: 60000
accept: */*
authorization: android-auth-<T>120
from: android-nlFGNlnhpoYgbhoj
gql-access-token: smartworld
session-key: android-session-<T>120
Content-Type: application/x-www-form-urlencoded
Host: polygon.net
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: <randomUserAgentOutput>

my telegram is: https://t.me/withoutdudes

**Comment by madamesr1337** [comment]
{"status":"error","message":"Error: Error solving the challenge. On step 'solving': No module named 'fcntl'","startTimestamp":1730929679.638392,"endTimestamp":1730929679.641323

I managed to solve almost all the errors, including the async one, but I can't run it on Windows since it's only for Linux.

**Comment by madamesr1337** [comment]
{
  "status": "error",
  "message": "Error: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 49607)",
  "startTimestamp": 1730924407.737345,
  "endTimestamp": 1730924408.775843
}

I also had errors like this on Linux. It didn't work at all.

**Comment by madamesr1337** [comment]
root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser # flare_bypass_server -b xxxxxxxxxxxx:8000
[2024-11-06 20:25:35 +0000] [1057175] [INFO] Starting gunicorn 23.0.0
[2024-11-06 20:25:35 +0000] [1057175] [INFO] Listening at: http://xxxxxxxxxxxx:8000 (1057175)
[2024-11-06 20:25:35 +0000] [1057175] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-11-06 20:25:35 +0000] [1057223] [INFO] Booting worker with pid: 1057223
[2024-11-06 20:25:35 +0000] [1057223] [INFO] Started server process [1057223]
[2024-11-06 20:25:35 +0000] [1057223] [INFO] Waiting for application startup.
[2024-11-06 20:25:35 +0000] [1057223] [INFO] Application startup complete.
2024-11-06 20:25:41,485 [nodriver.core.browser] [INFO]: starting
        executable :/bin/google-chrome

arguments:
--remote-allow-origins=*
        --no-first-run
        --no-service-autorun
        --no-default-browser-check
        --homepage=about:blank
        --no-pings
        --password-store=basic
        --disable-infobars
        --disable-breakpad
        --disable-component-update
        --disable-backgrounding-occluded-windows
        --disable-renderer-backgrounding
        --disable-background-networking
        --disable-dev-shm-usage
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --disable-search-engine-choice-screen
        --user-data-dir=/tmp/uc_34f0xd0r
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --proxy-server=string
        --no-sandbox
        --remote-debugging-host=127.0.0.1
        --remote-debugging-port=42023
2024-11-06 20:25:42,251 [nodriver.core.browser] [INFO]: enabling autodiscover targets
2024-11-06 20:25:42,263 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=string), timeout=60.0
2024-11-06 20:25:42,536 [root] [INFO]: Close webdriver
2024-11-06 20:25:42,537 [root] [ERROR]: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 42023)
Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 42023)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 375, in _resolve_challenge_impl
    await self.save_screenshot('evil_logic')
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 203, in save_screenshot
    await self._driver.save_screenshot(screenshot_file_without_ext + ".png")
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/browser_wrapper.py", line 139, in save_screenshot
    await self._page.save_screenshot(image_path)
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/tab.py", line 1196, in save_screenshot
    await self.sleep()  # update the target's url
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 317, in sleep
    await self.update_target()
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 392, in update_target
    target_info: cdp.target.TargetInfo = await self.send(
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 411, in send
    await self.aopen()
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 285, in aopen
    self.websocket = await websockets.connect(
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 42023)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 251, in _resolve_challenge
    return await self._resolve_challenge_impl(req, start_time)
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 423, in _resolve_challenge_impl
    raise Solver.Exception(str(e), step=step)
flare_bypasser.flare_bypasser.Solver.Exception: [Errno 111] Connect call failed ('127.0.0.1', 42023)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
    solve_response = await solver.solve(solve_request)
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 222, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), timeout=req.max_timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 261, in _resolve_challenge
    raise Solver.Exception(error_message, step=e.step)
flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 42023)

^C[2024-11-06 20:25:50 +0000] [1057175] [INFO] Handling signal: int
[2024-11-06 20:25:50 +0000] [1057223] [INFO] Shutting down
[2024-11-06 20:25:50 +0000] [1057223] [INFO] Waiting for application shutdown.
[2024-11-06 20:25:50 +0000] [1057223] [INFO] Application shutdown complete.
[2024-11-06 20:25:50 +0000] [1057223] [INFO] Finished server process [1057223]
[2024-11-06 20:25:50 +0000] [1057175] [ERROR] Worker (pid:1057223) was sent SIGINT!
[2024-11-06 20:25:50 +0000] [1057175] [INFO] Shutting down: Master
root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser # ^C
root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser # sudo ufw status
sudo ufw allow 42023
sudo: ufw: command not found
sudo: ufw: command not found
root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser # ufw status
Command 'ufw' not found, but can be installed with:
apt install ufw
root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser #
apt install ufw^C
root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser # flare_bypass_server -b xxxxxxxxx:8000
[2024-11-06 20:33:33 +0000] [1057586] [INFO] Starting gunicorn 23.0.0
[2024-11-06 20:33:33 +0000] [1057586] [INFO] Listening at: http://xxxxxxxxx:8000 (1057586)
[2024-11-06 20:33:33 +0000] [1057586] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-11-06 20:33:33 +0000] [1057634] [INFO] Booting worker with pid: 1057634
[2024-11-06 20:33:33 +0000] [1057634] [INFO] Started server process [1057634]
[2024-11-06 20:33:33 +0000] [1057634] [INFO] Waiting for application startup.
[2024-11-06 20:33:33 +0000] [1057634] [INFO] Application startup complete.
2024-11-06 20:33:40,868 [nodriver.core.browser] [INFO]: starting
        executable :/bin/google-chrome

arguments:
--remote-allow-origins=*
        --no-first-run
        --no-service-autorun
        --no-default-browser-check
        --homepage=about:blank
        --no-pings
        --password-store=basic
        --disable-infobars
        --disable-breakpad
        --disable-component-update
        --disable-backgrounding-occluded-windows
        --disable-renderer-backgrounding
        --disable-background-networking
        --disable-dev-shm-usage
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --disable-search-engine-choice-screen
        --user-data-dir=/tmp/uc_oo6k6u3y
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --proxy-server=string
        --no-sandbox
        --remote-debugging-host=127.0.0.1
        --remote-debugging-port=38719
2024-11-06 20:33:41,634 [nodriver.core.browser] [INFO]: enabling autodiscover targets
2024-11-06 20:33:41,647 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=string), timeout=60.0
2024-11-06 20:33:42,314 [root] [INFO]: Screenshot saved to '0_evil_logic'
2024-11-06 20:33:42,352 [uc.connection] [INFO]: KeyError: ('DOM.scrollableFlagUpdated',)  during parsing of json from event : {'method': 'DOM.scrollableFlagUpdated', 'params': {'nodeId': 1, 'isScrollable': False}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 649, in listener_loop
    event = cdp.util.parse_json_event(message)
  File "/usr/local/lib/python3.10/dist-packages/nodriver/cdp/util.py", line 19, in parse_json_event
    return _event_parsers[json["method"]].from_json(json["params"])
KeyError: 'DOM.scrollableFlagUpdated'
2024-11-06 20:33:44,260 [root] [INFO]: Screenshot saved to '1_after_challenge_check'
2024-11-06 20:33:44,610 [root] [INFO]: Screenshot saved to '2_no_challenge_found'
2024-11-06 20:33:44,610 [root] [INFO]: Challenge not detected!
2024-11-06 20:33:44,756 [root] [INFO]: Cookies got
2024-11-06 20:33:45,143 [root] [INFO]: Screenshot saved to '3_finish'
2024-11-06 20:33:45,143 [root] [INFO]: Solving finished
2024-11-06 20:33:45,143 [root] [INFO]: Close webdriver
2024-11-06 20:33:45,144 [nodriver.core.browser] [INFO]: terminated browser with pid 1057641 successfully
2024-11-06 20:33:45,144 [root] [INFO]: Solve result: <flare_bypasser.flare_bypasser.Response object at 0x7fab7f492ef0>
2024-11-06 20:34:07,910 [nodriver.core.browser] [INFO]: starting
        executable :/bin/google-chrome

arguments:
--remote-allow-origins=*
        --no-first-run
        --no-service-autorun
        --no-default-browser-check
        --homepage=about:blank
        --no-pings
        --password-store=basic
        --disable-infobars
        --disable-breakpad
        --disable-component-update
        --disable-backgrounding-occluded-windows
        --disable-renderer-backgrounding
        --disable-background-networking
        --disable-dev-shm-usage
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --disable-search-engine-choice-screen
        --user-data-dir=/tmp/uc_bdcpv10b
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --proxy-server=string
        --no-sandbox
        --remote-debugging-host=127.0.0.1
        --remote-debugging-port=47227
2024-11-06 20:34:08,668 [nodriver.core.browser] [INFO]: enabling autodiscover targets
2024-11-06 20:34:08,675 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=string), timeout=60.0
2024-11-06 20:34:08,946 [root] [INFO]: Close webdriver
2024-11-06 20:34:08,946 [root] [ERROR]: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 47227)
Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 47227)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 375, in _resolve_challenge_impl
    await self.save_screenshot('evil_logic')
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 203, in save_screenshot
    await self._driver.save_screenshot(screenshot_file_without_ext + ".png")
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/browser_wrapper.py", line 139, in save_screenshot
    await self._page.save_screenshot(image_path)
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/tab.py", line 1196, in save_screenshot
    await self.sleep()  # update the target's url
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 317, in sleep
    await self.update_target()
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 392, in update_target
    target_info: cdp.target.TargetInfo = await self.send(
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 411, in send
    await self.aopen()
  File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 285, in aopen
    self.websocket = await websockets.connect(
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 47227)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 251, in _resolve_challenge
    return await self._resolve_challenge_impl(req, start_time)
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 423, in _resolve_challenge_impl
    raise Solver.Exception(str(e), step=step)
flare_bypasser.flare_bypasser.Solver.Exception: [Errno 111] Connect call failed ('127.0.0.1', 47227)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
    solve_response = await solver.solve(solve_request)
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 222, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), timeout=req.max_timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 261, in _resolve_challenge
    raise Solver.Exception(error_message, step=e.step)
flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 47227)

**Comment by madamesr1337** [comment]
/usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'flare_bypasser.flare_bypass_server' found in sys.modules after import of package 'flare_bypasser', but prior to execution of 'flare_bypasser.flare_bypass_server'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[2024-11-06 21:03:10 +0000] [1099566] [INFO] Starting gunicorn 23.0.0
[2024-11-06 21:03:10 +0000] [1099566] [INFO] Listening at: http://xxxxxxxxx:8000 (1099566)
[2024-11-06 21:03:10 +0000] [1099566] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Booting worker with pid: 1099614
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Started server process [1099614]
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Waiting for application startup.
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Application startup complete.
module 'asyncio' has no attribute 'timeout'
Traceback (most recent call last):
  File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
    solve_response = await solver.solve(solve_request)
  File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypasser.py", line 223, in solve
    async with asyncio.timeout(req.max_timeout):
AttributeError: module 'asyncio' has no attribute 'timeout'

module 'asyncio' has no attribute 'timeout'
Traceback (most recent call last):
  File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
    solve_response = await solver.solve(solve_request)
  File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypasser.py", line 223, in solve
    async with asyncio.timeout(req.max_timeout):
AttributeError: module 'asyncio' has no attribute 'timeout'

**Comment by yoori** [comment]
Hi @madamesr1337 I fixed problem with python3.9 - you can try.
For debug Ubuntu-2204-jammy-amd64-base case I will add chrome running logs - it is in progress
Windows in progress too

**Comment by yoori** [comment]
> {"status":"error","message":"Error: Error solving the challenge. On step 'solving': No module named 'fcntl'","startTimestamp":1730929679.638392,"endTimestamp":1730929679.641323
> 
> I managed to solve almost all the errors, including the async one, but I can't run it on Windows since it's only for Linux.

Can you provide "docker compose logs" or flare_bypass_server output (if you run without docker) ?

**Comment by yoori** [comment]
> /usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'flare_bypasser.flare_bypass_server' found in sys.modules after import of package 'flare_bypasser', but prior to execution of 'flare_bypasser.flare_bypass_server'; this may result in unpredictable behaviour warn(RuntimeWarning(msg)) [2024-11-06 21:03:10 +0000] [1099566] [INFO] Starting gunicorn 23.0.0 [2024-11-06 21:03:10 +0000] [1099566] [INFO] Listening at: http://xxxxxxxxx:8000 (1099566) [2024-11-06 21:03:10 +0000] [1099566] [INFO] Using worker: uvicorn.workers.UvicornWorker [2024-11-06 21:03:10 +0000] [1099614] [INFO] Booting worker with pid: 1099614 [2024-11-06 21:03:10 +0000] [1099614] [INFO] Started server process [1099614] [2024-11-06 21:03:10 +0000] [1099614] [INFO] Waiting for application startup. [2024-11-06 21:03:10 +0000] [1099614] [INFO] Application startup complete. module 'asyncio' has no attribute 'timeout' Traceback (most recent call last): File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request solve_response = await solver.solve(solve_request) File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypasser.py", line 223, in solve async with asyncio.timeout(req.max_timeout): AttributeError: module 'asyncio' has no attribute 'timeout'
> 
> module 'asyncio' has no attribute 'timeout' Traceback (most recent call last): File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request solve_response = await solver.solve(solve_request) File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypasser.py", line 223, in solve async with asyncio.timeout(req.max_timeout): AttributeError: module 'asyncio' has no attribute 'timeout'

I fixed problem with python3.9 - you can try.

**Comment by yoori** [comment]
> root@Ubuntu-2204-jammy-amd64-base ~/flare-bypasser # flare_bypass_server -b xxxxxxxxx:8000 [2024-11-06 20:33:33 +0000] [1057586] [INFO] Starting gunicorn 23.0.0 [2024-11-06 20:33:33 +0000] [1057586] [INFO] Listening at: http://xxxxxxxxx:8000 (1057586) [2024-11-06 20:33:33 +0000] [1057586] [INFO] Using worker: uvicorn.workers.UvicornWorker [2024-11-06 20:33:33 +0000] [1057634] [INFO] Booting worker with pid: 1057634 [2024-11-06 20:33:33 +0000] [1057634] [INFO] Started server process [1057634] [2024-11-06 20:33:33 +0000] [1057634] [INFO] Waiting for application startup. [2024-11-06 20:33:33 +0000] [1057634] [INFO] Application startup complete. 2024-11-06 20:33:40,868 [nodriver.core.browser] [INFO]: starting executable :/bin/google-chrome
> 
> arguments: --remote-allow-origins=* --no-first-run --no-service-autorun --no-default-browser-check --homepage=about:blank --no-pings --password-store=basic --disable-infobars --disable-breakpad --disable-component-update --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --disable-background-networking --disable-dev-shm-usage --disable-features=IsolateOrigins,site-per-process --disable-session-crashed-bubble --disable-search-engine-choice-screen --user-data-dir=/tmp/uc_oo6k6u3y --disable-features=IsolateOrigins,site-per-process --disable-session-crashed-bubble --proxy-server=string --no-sandbox --remote-debugging-host=127.0.0.1 --remote-debugging-port=38719 2024-11-06 20:33:41,634 [nodriver.core.browser] [INFO]: enabling autodiscover targets 2024-11-06 20:33:41,647 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=string), timeout=60.0 2024-11-06 20:33:42,314 [root] [INFO]: Screenshot saved to '0_evil_logic' 2024-11-06 20:33:42,352 [uc.connection] [INFO]: KeyError: ('DOM.scrollableFlagUpdated',) during parsing of json from event : {'method': 'DOM.scrollableFlagUpdated', 'params': {'nodeId': 1, 'isScrollable': False}} Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 649, in listener_loop event = cdp.util.parse_json_event(message) File "/usr/local/lib/python3.10/dist-packages/nodriver/cdp/util.py", line 19, in parse_json_event return _event_parsers[json["method"]].from_json(json["params"]) KeyError: 'DOM.scrollableFlagUpdated' 2024-11-06 20:33:44,260 [root] [INFO]: Screenshot saved to '1_after_challenge_check' 2024-11-06 20:33:44,610 [root] [INFO]: Screenshot saved to '2_no_challenge_found' 2024-11-06 20:33:44,610 [root] [INFO]: Challenge not detected! 2024-11-06 20:33:44,756 [root] [INFO]: Cookies got 2024-11-06 20:33:45,143 [root] [INFO]: Screenshot saved to '3_finish' 2024-11-06 20:33:45,143 [root] [INFO]: Solving finished 2024-11-06 20:33:45,143 [root] [INFO]: Close webdriver 2024-11-06 20:33:45,144 [nodriver.core.browser] [INFO]: terminated browser with pid 1057641 successfully 2024-11-06 20:33:45,144 [root] [INFO]: Solve result: <flare_bypasser.flare_bypasser.Response object at 0x7fab7f492ef0> 2024-11-06 20:34:07,910 [nodriver.core.browser] [INFO]: starting executable :/bin/google-chrome
> 
> arguments: --remote-allow-origins=* --no-first-run --no-service-autorun --no-default-browser-check --homepage=about:blank --no-pings --password-store=basic --disable-infobars --disable-breakpad --disable-component-update --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --disable-background-networking --disable-dev-shm-usage --disable-features=IsolateOrigins,site-per-process --disable-session-crashed-bubble --disable-search-engine-choice-screen --user-data-dir=/tmp/uc_bdcpv10b --disable-features=IsolateOrigins,site-per-process --disable-session-crashed-bubble --proxy-server=string --no-sandbox --remote-debugging-host=127.0.0.1 --remote-debugging-port=47227 2024-11-06 20:34:08,668 [nodriver.core.browser] [INFO]: enabling autodiscover targets 2024-11-06 20:34:08,675 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=string), timeout=60.0 2024-11-06 20:34:08,946 [root] [INFO]: Close webdriver 2024-11-06 20:34:08,946 [root] [ERROR]: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 47227) Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 47227) Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 375, in _resolve_challenge_impl await self.save_screenshot('evil_logic') File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 203, in save_screenshot await self._driver.save_screenshot(screenshot_file_without_ext + ".png") File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/browser_wrapper.py", line 139, in save_screenshot await self._page.save_screenshot(image_path) File "/usr/local/lib/python3.10/dist-packages/nodriver/core/tab.py", line 1196, in save_screenshot await self.sleep() # update the target's url File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 317, in sleep await self.update_target() File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 392, in update_target target_info: cdp.target.TargetInfo = await self.send( File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 411, in send await self.aopen() File "/usr/local/lib/python3.10/dist-packages/nodriver/core/connection.py", line 285, in aopen self.websocket = await websockets.connect( File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/client.py", line 654, in **await_impl** _transport, protocol = await self._create_connection() File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection raise exceptions[0] File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection sock = await self._connect_sock( File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock await self.sock_connect(sock, address) File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect return await fut File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb raise OSError(err, f'Connect call failed {address}') ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 47227)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 251, in _resolve_challenge return await self._resolve_challenge_impl(req, start_time) File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 423, in _resolve_challenge_impl raise Solver.Exception(str(e), step=step) flare_bypasser.flare_bypasser.Solver.Exception: [Errno 111] Connect call failed ('127.0.0.1', 47227)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request solve_response = await solver.solve(solve_request) File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 222, in solve res = await asyncio.wait_for(self._resolve_challenge(req), timeout=req.max_timeout) File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for return fut.result() File "/usr/local/lib/python3.10/dist-packages/flare_bypasser/flare_bypasser.py", line 261, in _resolve_challenge raise Solver.Exception(error_message, step=e.step) flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 47227)

Looks like problem with chrome start - I work on print chrome logs if its start failed

**Comment by yoori** [comment]
> {"status":"error","message":"Error: Error solving the challenge. On step 'solving': No module named 'fcntl'","startTimestamp":1730929679.638392,"endTimestamp":1730929679.641323
> 
> I managed to solve almost all the errors, including the async one, but I can't run it on Windows since it's only for Linux.

Please, try latest version - fixed bug with xvfb usage on windows platform.

**Comment by yoori** [comment]
> { "status": "error", "message": "Error: Error solving the challenge. On step 'navigate to url': [Errno 111] Connect call failed ('127.0.0.1', 49607)", "startTimestamp": 1730924407.737345, "endTimestamp": 1730924408.775843 }
> 
> I also had errors like this on Linux. It didn't work at all.

For diagnostic this problem to exception added chrome process output, can you provide `docker compose logs` or `flare_bypass_server` command output (if you don't use docker)

**Comment by yoori** [comment]
Please, check last version (here much changes : windows support fix, arch support, py3.9 support fix), if some problem open issue. Thanks
