### ISSUE TITLE
Zendriver issue with listener loop interruption

### ISSUE THREAD

**Issue by yoori** [yoori/flare-bypasser#30]
```
flare-bypasser  | 2024-12-08 23:36:50,077 [asyncio] [ERROR]: Task exception was never retrieved
flare-bypasser  | future: <Task finished name='Task-35' coro=<Listener.listener_loop() done, defined at /usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/connection.py:606> exception
=InvalidStateError('invalid state')>
flare-bypasser  | Traceback (most recent call last):
flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/connection.py", line 126, in __call__
flare-bypasser  |     self.__cdp_obj__.send(response["result"])
flare-bypasser  | StopIteration: (FrameId('B1214E78BA72CC5D4850EE688E8653D1'), LoaderId('EDF9E37B9AFCDD3D690E47D2FFA5CAC0'), 'net::ERR_ABORTED')
flare-bypasser  | 
flare-bypasser  | During handling of the above exception, another exception occurred:
flare-bypasser  | 
flare-bypasser  | Traceback (most recent call last):
flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/connection.py", line 653, in listener_loop
flare-bypasser  |     tx(**message)
flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/connection.py", line 129, in __call__
flare-bypasser  |     return self.set_result(e.value)
flare-bypasser  |            ^^^^^^^^^^^^^^^^^^^^^^^^
flare-bypasser  | asyncio.exceptions.InvalidStateError: invalid state
flare-bypasser  | 2024-12-08 23:37:36,337 [flare_bypasser.flare_bypasser] [INFO]: fork #0, Close webdriver
flare-bypasser  | Processing timeout (max_timeout=60.0)
flare-bypasser  | Traceback (most recent call last):
flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 404, in _wait_first
flare-bypasser  |     finished, to_cancel_tasks = await asyncio.wait(
flare-bypasser  |                                 ^^^^^^^^^^^^^^^^^^^
flare-bypasser  |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 428, in wait
flare-bypasser  |     return await _wait(fs, timeout, return_when, loop)
flare-bypasser  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flare-bypasser  |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 535, in _wait
flare-bypasser  |     await waiter
flare-bypasser  | asyncio.exceptions.CancelledError

```

**Comment by yoori** [comment]
Fixed in [this commit](https://github.com/yoori/flare-bypasser/commit/59f89758c95a5775c50e39d0f14e5b8356aded2f)
