### ISSUE TITLE
Field solution.status should be int

### ISSUE THREAD

**Issue by felipemarinho97** [yoori/flare-bypasser#33]
```
{
  "status": "ok",
  "message": "Challenge not detected!",
  "startTimestamp": 1734369809.216798,
  "endTimestamp": 1734369813.229656,
  "solution": {
    "status": "ok", <- THIS FIELD SHOULD BE THE STATUS CODE: 200
    "url": "https://example.com/",
    "cookies": [],
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "response": "<!DOCTYPE html><html><head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href=\"https://www.iana.org/domains/example\">More information...</a></p>\n</div>\n\n\n</body></html>"
  }
}
```

I am unable to integrate with a application that uses the flaresolverr API.

**Comment by yoori** [comment]
[fixed](https://github.com/yoori/flare-bypasser/commit/69a98802d90397707d7954ff6bd8dbbdc6b888bc)
please, try latest version

**Comment by felipemarinho97** [comment]
@yoori latest version is broken

```
flarebypasser    | 2024-12-16 18:53:56,454 [flare_bypasser.flare_bypasser] [ERROR]: fork #0, Error solving the challenge. On platform linux at step 'browser init':
flarebypasser    | On user-agent getting:
flarebypasser    | Traceback (most recent call last):
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 166, in get_user_agent
flarebypasser    |     return await asyncio.wait_for(
flarebypasser    |            ^^^^^^^^^^^^^^^^^^^^^^^
flarebypasser    |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
flarebypasser    |     return fut.result()
flarebypasser    |            ^^^^^^^^^^^^
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 560, in get_user_agent
flarebypasser    |     driver: BrowserWrapper = await BrowserWrapper.create(
flarebypasser    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 115, in create
flarebypasser    |     zendriver_driver = await zendriver.Browser.create(config)
flarebypasser    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/browser.py", line 92, in create
flarebypasser    |     await instance.start()
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/browser.py", line 372, in start
flarebypasser    |     await self._stop_process()
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/zendriver_flare_bypasser/core/browser.py", line 590, in _stop_process
flarebypasser    |     self._process.terminate()
flarebypasser    |   File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 143, in terminate
flarebypasser    |     self._transport.terminate()
flarebypasser    |   File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 149, in terminate
flarebypasser    |     self._check_proc()
flarebypasser    |   File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 142, in _check_proc
flarebypasser    |     raise ProcessLookupError()
flarebypasser    | ProcessLookupError
flarebypasser    |
flarebypasser    | The above exception was the direct cause of the following exception:
flarebypasser    |
flarebypasser    | Traceback (most recent call last):
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 279, in process_solve_request
flarebypasser    |     (solve_response, _skipped_results, _exceptions), user_agent = await asyncio.gather(
flarebypasser    |                                                                   ^^^^^^^^^^^^^^^^^^^^^
flarebypasser    |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 176, in get_user_agent
flarebypasser    |     raise Exception("On user-agent getting: " + str(e)) from e
flarebypasser    | Exception: On user-agent getting:
flarebypasser    |
```

my curl:
```
$ curl -L -X POST 'http://localhost:8080/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url": "http://example.com",
  "maxTimeout": "60000",
  "session": "dumb"
}'
{"status":"error","message":"Error: On user-agent getting: ","startTimestamp":1734375233.58058,"endTimestamp":1734375236.457072}
```
