### ISSUE TITLE
 Checkbox isn't found

### ISSUE THREAD

**Issue by shawnlocal** [yoori/flare-bypasser#35]
[flare_bypasser.flare_bypasser] [INFO]: fork #0, To check checkbox presense
[flare_bypasser.flare_bypasser] [INFO]: fork #0, Checkbox isn't found
[flare_bypasser.flare_bypasser] [INFO]: fork #0, Close webdriver
Processing timeout (max_timeout=55.0)
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypasser.py", line 313, in _resolve_challenge
    return await self._resolve_challenge_impl(req, start_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypasser.py", line 518, in _resolve_challenge_impl
    await self._challenge_wait_and_click_loop()
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypasser.py", line 459, in _challenge_wait_and_click_loop
    await asyncio.sleep(_SHORT_TIMEOUT)
  File "C:\Program Files\Python312\Lib\asyncio\tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypasser.py", line 278, in solve
    res = await asyncio.wait_for(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypass_server.py", line 279, in process_solve_request
    (solve_response, _skipped_results, _exceptions), user_agent = await asyncio.gather(
                                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypass_server.py", line 147, in wait_first_non_exception
    raise e
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypass_server.py", line 139, in wait_first_non_exception
    res = await f
          ^^^^^^^
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypass_server.py", line 191, in solve
    return await solver.solve(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\AppData\Roaming\Python\Python312\site-packages\flare_bypasser\flare_bypasser.py", line 283, in solve
    raise Exception("Processing timeout (max_timeout=" + str(req.max_timeout) + ")")
Exception: Processing timeout (max_timeout=55.0)

←[32mINFO←[0m:     127.0.0.1:56199 - "←[1mPOST /v1 HTTP/1.1←[0m" ←[32m200 OK←[0m

**Comment by drmetro09** [comment]
Same error

**Comment by yoori** [comment]
Please ! Add full log or web site url, that you try to solve - without that I can't help ! )
You can provide part of full log after record : `Solve request: {'cmd': 'get_cookies', 'url': '...`, if don't want to publish full log
