### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'timeout'

### ISSUE THREAD

**Issue by madamesr1337** [yoori/flare-bypasser#5]
/usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'flare_bypasser.flare_bypass_server' found in sys.modules after import of package 'flare_bypasser', but prior to execution of 'flare_bypasser.flare_bypass_server'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))
[2024-11-06 21:03:10 +0000] [1099566] [INFO] Starting gunicorn 23.0.0
[2024-11-06 21:03:10 +0000] [1099566] [INFO] Listening at: http://xxxxxxxxx:8000/ (1099566)
[2024-11-06 21:03:10 +0000] [1099566] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Booting worker with pid: 1099614
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Started server process [1099614]
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Waiting for application startup.
[2024-11-06 21:03:10 +0000] [1099614] [INFO] Application startup complete.
module 'asyncio' has no attribute 'timeout'
Traceback (most recent call last):
File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
solve_response = await solver.solve(solve_request)
File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypasser.py", line 223, in solve
async with asyncio.timeout(req.max_timeout):
AttributeError: module 'asyncio' has no attribute 'timeout'

module 'asyncio' has no attribute 'timeout'
Traceback (most recent call last):
File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
solve_response = await solver.solve(solve_request)
File "/root/myenv/lib/python3.9/site-packages/flare_bypasser/flare_bypasser.py", line 223, in solve
async with asyncio.timeout(req.max_timeout):
AttributeError: module 'asyncio' has no attribute 'timeout'

**Comment by jacket430** [comment]
Upgrade your Python install, 3.9 doesn't include a lot of the asyncio updates.

**Comment by yoori** [comment]
Please, update and try - I restored python3.9 compatibility
