### ISSUE TITLE
Unusable on Windows because of fnctl usage

### ISSUE THREAD

**Issue by LightSeek3r** [yoori/flare-bypasser#6]
Here's the logs:

```
←[32mINFO←[0m:     Started server process [←[36m26024←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
2024-11-07 13:18:36,757 [root] [INFO]: Close webdriver
2024-11-07 13:18:36,758 [root] [ERROR]: Error solving the challenge. On step 'solving': No module named 'fcntl'
Error solving the challenge. On step 'solving': No module named 'fcntl'
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 251, in _resolve_challenge
    self._driver = await BrowserWrapper.create(use_proxy, disable_gpu = self._disable_gpu)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\browser_wrapper.py", line 66, in create
    BrowserWrapper.start_xvfb_display()
  File "C:\Python312\Lib\site-packages\flare_bypasser\browser_wrapper.py", line 60, in start_xvfb_display
    from xvfbwrapper import Xvfb
  File "C:\Python312\Lib\site-packages\xvfbwrapper.py", line 15, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypass_server.py", line 82, in process_solve_request
    solve_response = await solver.solve(solve_request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 226, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), req.max_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 269, in _resolve_challenge
    raise Solver.Exception(error_message)
flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On step 'solving': No module named 'fcntl'
```

**Comment by yoori** [comment]
Please, try latest version (win support fixed)

**Comment by LightSeek3r** [comment]
I re-cloned the repo, ran it (`flare_bypass_server`), directed Jackett to `http://127.0.0.1:8000/`, tested one indexer and immediately got:

```
INFO:     Started server process [23440]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-11-07 16:33:13,015 [root] [INFO]: Close webdriver
2024-11-07 16:33:13,016 [root] [ERROR]: Error solving the challenge. On step 'solving': No module named 'fcntl'
Error solving the challenge. On step 'solving': No module named 'fcntl'
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 251, in _resolve_challenge
    self._driver = await BrowserWrapper.create(use_proxy, disable_gpu = self._disable_gpu)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\browser_wrapper.py", line 66, in create
    BrowserWrapper.start_xvfb_display()
  File "C:\Python312\Lib\site-packages\flare_bypasser\browser_wrapper.py", line 60, in start_xvfb_display
    from xvfbwrapper import Xvfb
  File "C:\Python312\Lib\site-packages\xvfbwrapper.py", line 15, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypass_server.py", line 82, in process_solve_request
    solve_response = await solver.solve(solve_request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 226, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), req.max_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 269, in _resolve_challenge
    raise Solver.Exception(error_message)
flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On step 'solving': No module named 'fcntl'

INFO:     127.0.0.1:61588 - "POST /v1 HTTP/1.1" 200 OK
```

**Comment by LightSeek3r** [comment]
Hello @yoori, thanks for the quick heads-up! I re-cloned the repo with your, ran the install (`pip install .`), ran the project (`flare_bypass_server`), directed Jackett to `http://127.0.0.1:8000/`, tested one indexer and immediately got:

```
2024-11-07 16:38:40,476 [nodriver.core.browser] [INFO]: starting
        executable :C:\Program Files\Google\Chrome\Application\chrome.exe

arguments:
--remote-allow-origins=*
        --no-first-run
        --no-service-autorun
        --no-default-browser-check
        --homepage=about:blank
        --no-pings
        --password-store=basic
        --disable-infobars
        --disable-breakpad
        --disable-component-update
        --disable-backgrounding-occluded-windows
        --disable-renderer-backgrounding
        --disable-background-networking
        --disable-dev-shm-usage
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --disable-search-engine-choice-screen
        --user-data-dir=C:\Users\extre\AppData\Local\Temp\uc_jwo_sjwu
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --headless
        --no-sandbox
        --remote-debugging-host=127.0.0.1
        --remote-debugging-port=55034
2024-11-07 16:38:40,953 [nodriver.core.browser] [INFO]: enabling autodiscover targets
2024-11-07 16:38:40,959 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=None), timeout=60.0
2024-11-07 16:38:40,959 [root] [INFO]: Close webdriver
2024-11-07 16:38:40,960 [nodriver.core.browser] [INFO]: terminated browser with pid 7224 successfully
2024-11-07 16:38:40,962 [root] [ERROR]: Error solving the challenge. On platform win32 at step 'navigate to url': list index out of range
Error solving the challenge. On platform win32 at step 'navigate to url': list index out of range
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 386, in _resolve_challenge_impl
    await self._driver.get(preprocessed_req.url)
  File "C:\Python312\Lib\site-packages\flare_bypasser\browser_wrapper.py", line 110, in get
    for tab_i, tab in enumerate(self._nodriver_driver):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nodriver\core\browser.py", line 532, in __iter__
    self._i = self.tabs.index(self.main_tab)
                              ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nodriver\core\browser.py", line 130, in main_tab
    return sorted(self.targets, key=lambda x: x.type_ == "page", reverse=True)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 257, in _resolve_challenge
    return await self._resolve_challenge_impl(req, start_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 437, in _resolve_challenge_impl
    raise Solver.Exception(str(e), step=step)
flare_bypasser.flare_bypasser.Solver.Exception: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypass_server.py", line 83, in process_solve_request
    solve_response = await solver.solve(solve_request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 226, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), req.max_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Python312\Lib\site-packages\flare_bypasser\flare_bypasser.py", line 271, in _resolve_challenge
    raise Solver.Exception(error_message, step=e.step)
flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On platform win32 at step 'navigate to url': list index out of range

←[32mINFO←[0m:     127.0.0.1:55033 - "←[1mPOST /v1 HTTP/1.1←[0m" ←[32m200 OK←[0m
2024-11-07 16:38:40,968 [asyncio] [ERROR]: Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Connection.aclose() done, defined at C:\Python312\Lib\site-packages\nodriver\core\connection.py:305> exception=ConnectionClosedError(None, Close(code=1000, reason=''), None)>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\nodriver\core\connection.py", line 313, in aclose
    await self.websocket.close()
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 1205, in write_frame
    await self.drain()
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 1194, in drain
    await self.ensure_open()
  File "C:\Python312\Lib\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
```
