### ISSUE TITLE
windows 10 error 

### ISSUE THREAD

**Issue by madamesr1337** [yoori/flare-bypasser#7]
i m use for try 

{
  "url": "https://torrentleech.pl/login.php?returnto=%2F",
  "cookies": [
    {}
  ],
  "maxTimeout": 60000,
  "proxy": "string"
}

result:

{
  "status": "error",
  "message": "Error: Error solving the challenge. On platform win32 at step 'set cookies': __init__() missing 2 required positional arguments: 'comment_url' and 'rest'",
  "startTimestamp": 1731008070.047801,
  "endTimestamp": 1731008080.266462
}

powershell result..

PS D:\COMBODOWNLAOD\flare-bypasser-main\flare-bypasser-main> flare_bypass_server
←[32mINFO←[0m:     Started server process [←[36m10168←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:1050 - "←[1mGET / HTTP/1.1←[0m" ←[31m404 Not Found←[0m
←[32mINFO←[0m:     127.0.0.1:1051 - "←[1mGET /docs HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:1051 - "←[1mGET /docs/openapi.json HTTP/1.1←[0m" ←[32m200 OK←[0m
2024-11-07 16:34:30,049 [nodriver.core.browser] [INFO]: starting
        executable :C:\Program Files\Google\Chrome\Application\chrome.exe

arguments:
--remote-allow-origins=*
        --no-first-run
        --no-service-autorun
        --no-default-browser-check
        --homepage=about:blank
        --no-pings
        --password-store=basic
        --disable-infobars
        --disable-breakpad
        --disable-component-update
        --disable-backgrounding-occluded-windows
        --disable-renderer-backgrounding
        --disable-background-networking
        --disable-dev-shm-usage
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --disable-search-engine-choice-screen
        --user-data-dir=C:\Users\Usuario\AppData\Local\Temp\uc__9vqd6_7
        --disable-features=IsolateOrigins,site-per-process
        --disable-session-crashed-bubble
        --proxy-server=string
        --headless
        --no-sandbox
        --remote-debugging-host=127.0.0.1
        --remote-debugging-port=1073
2024-11-07 16:34:31,999 [nodriver.core.browser] [INFO]: enabling autodiscover targets
2024-11-07 16:34:32,009 [root] [INFO]: New instance of webdriver has been created to perform the request (proxy=string), timeout=60.0
2024-11-07 16:34:37,796 [root] [INFO]: Screenshot saved to '0_evil_logic'
2024-11-07 16:34:37,796 [root] [INFO]: Close webdriver
2024-11-07 16:34:38,026 [nodriver.core.browser] [INFO]: terminated browser with pid 180 successfully
2024-11-07 16:34:38,026 [root] [ERROR]: Error solving the challenge. On platform win32 at step 'set cookies': __init__() missing 2 required positional arguments: 'comment_url' and 'rest'
Error solving the challenge. On platform win32 at step 'set cookies': __init__() missing 2 required positional arguments: 'comment_url' and 'rest'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\flare_bypasser.py", line 396, in _resolve_challenge_impl
    await self._driver.set_cookies(preprocessed_req.cookies)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\browser_wrapper.py", line 164, in set_cookies
    cookie_jar.set_cookie(http.cookiejar.Cookie(
TypeError: __init__() missing 2 required positional arguments: 'comment_url' and 'rest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\flare_bypasser.py", line 257, in _resolve_challenge
    return await self._resolve_challenge_impl(req, start_time)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\flare_bypasser.py", line 437, in _resolve_challenge_impl
    raise Solver.Exception(str(e), step=step)
flare_bypasser.flare_bypasser.Solver.Exception: __init__() missing 2 required positional arguments: 'comment_url' and 'rest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\flare_bypass_server.py", line 83, in process_solve_request
    solve_response = await solver.solve(solve_request)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\flare_bypasser.py", line 226, in solve
    res = await asyncio.wait_for(self._resolve_challenge(req), req.max_timeout)
  File "C:\Program Files (x86)\Python39-32\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\flare_bypasser-0.1.25-py3.9.egg\flare_bypasser\flare_bypasser.py", line 271, in _resolve_challenge
    raise Solver.Exception(error_message, step=e.step)
flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On platform win32 at step 'set cookies': __init__() missing 2 required positional arguments: 'comment_url' and 'rest'

←[32mINFO←[0m:     127.0.0.1:1054 - "←[1mPOST /get_cookies HTTP/1.1←[0m" ←[32m200 OK←[0m

**Comment by yoori** [comment]
Remove `{}` from cookies array (that you send). I will add to api strict requirements for cookie element - it can’t be empty definitely

**Comment by yoori** [comment]
Fixed in [a1f9d40e](https://github.com/yoori/flare-bypasser/commit/a1f9d40e40627e5ace8fd4d12a7d57ae4670539f), please check version after this commit
